name: nava_demon_lords_diary
description: Dark fantasy anime-themed task, mood, and journal app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/adaptive-icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/adaptive-icon.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/adaptive-icon.png
  min_sdk_android: 21
